name: Generate configuration

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 1 # Every Monday

concurrency: postCommit

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  generateConfiguration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - name: Install dependencies
        run: npm run ci
      - name: Reload the cache
        uses: actions/cache@v3
        with:
          path: .cache
          key: cache@${{ github.ref }}
      - name: Prepare git
        run: node scripts/postCommit/prepareGit.js
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      - name: Generate unrecognizable features
        run: node scripts/generateUnrecognizableFeatures/index.js
      - name: Generate user rights schema
        run: node scripts/generateUserRightsSchema/index.js
      - name: Show git status & push
        run: node scripts/postCommit/push.js
